# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-20 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_bdd_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bdd_chiffre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chiffres clé',
                'ordering': ['id'],
            },
        ),
    ]
