# Generated by Django 2.1.7 on 2019-12-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0007_auto_20191129_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bdd_reseaux',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lien', models.CharField(default=' ', max_length=400)),
                ('titre', models.CharField(default=' ', max_length=400)),
                ('logo', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'verbose_name': 'Réseaux',
                'ordering': ['id'],
            },
        ),
    ]
