# Generated by Django 2.1.7 on 2019-12-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0008_bdd_reseaux'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdd_reseaux',
            options={'ordering': ['id'], 'verbose_name': 'Réseaux lien'},
        ),
        migrations.RenameField(
            model_name='bdd_reseaux',
            old_name='titre',
            new_name='réseau',
        ),
    ]
