# Generated by Django 2.1.7 on 2019-12-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0009_auto_20191208_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bdd_reseaux',
            old_name='réseau',
            new_name='nom',
        ),
    ]
