# Generated by Django 2.1.7 on 2019-12-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0010_auto_20191208_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdd_reseaux',
            name='logo',
        ),
    ]
